#!/usr/bin/env ruby

lib = File.exists?('/usr/local/lib64') ? 'lib64' : 'lib'

cmds = []

cmds << "/etc/init.d/mongod stop"
cmds << "cp -R ./bin/* /usr/local/bin/"
cmds << "cp -R ./#{lib}/* /usr/local/#{lib}/"
cmds << "cp -R ./include/* /usr/local/include/"
cmds << "/etc/init.d/mongod start"

system(cmds.join('&&'))
